#!/bin/sh

if test $# -gt 1 
then
	echo "Enclose message in '' to prevent shell argument issues. Discarded."
	exit 1
fi
if test $# -eq 0
then
	echo -n "Task summary: [93m(\".\" to cancel)[0m " >`tty`
	read input
	case "$input" in
		\.) exit 1;;
	esac
	set "$input"

fi
sed -i "1i `date -I`\t`date +%T`\t$@" LOG 
exit 0
