Provisional Goals
=================

Incomplete
----------

Goal 1::
	Approval of the full thesis proposal by the appropriate
	departmental/faculty postgraduate committee.
Goal 2::
	A substantial piece of written work, such as a literature review,
	completed to the satisfaction of the main supervisor.
Goal 3::
	Presentation of the proposal and/or work in progress to an appropriate
	forum e.g. seminar, research group, conference, to the satisfaction of
	the supervisors.
Goal 10::
	Write a review of existing methods and literature on approaches to
	distributed computing with R and current solutions in other
	language/systems with similar goals for statistical modelling like
	Python or Spark, to the satisfaction of the primary supervisor.
Goal 11::
	Implement a prototype R software capable of performing operations on
	multiple chunks of data in parallel on different machines and use the
	prototype to implement one statistical model, to the satisfaction of
	the primary supervisor.
Goal 12::
	Attend at least 10 relevant research presentations per annum (student
	needs to verify participation by filling out and handing in the
	departmental attendance form for each presentation to the Statistics
	Department office) (2/10)
Goal 13::
	Participate in the Department of Statistics PhD Talks Day and/or give a
	departmental seminar, to the satisfaction of the main supervisor. Also,
	maintain a personal profile page (www.directory.auckland.ac.nz),
	providing information on scholarly activities and objectives to the
	satisfaction of the main supervisor and a Department of Statistics PhD
	Officer
Goal 14::
	Attendance at one of the Faculty of Science Doctoral Induction Workshops. 

Complete
--------

Goal 4::
	Ethics approval/s and/or permissions obtained for the research (if
	required).
Goal 5::
	Attendance at one of the Doctoral Skills Programme Induction Days.
Goal 6::
	Successful completion of the Academic Integrity Module.
Goal 7::
	A needs analysis to determine training and other requirements that must
	be completed before candidature can be confirmed.
Goal 8::
	Completion of a health and safety risk assessment and training for any
	laboratory/studio/field and related work activities.
Goal 9::
	Undertake Diagnostic English Language Needs Assessment (DELNA) online
	screening. If a full assessment is advised, complete full diagnostic
	test and participate in any language enrichment recommended by the
	DELNA Language Advisor.
