@startuml

class chunk {
        -dataState
        {abstract} +data() : <data>
        {abstract} +do(function, ...chunk) : chunk
}

abstract class dataState {
        +data()
}

class dataComputed {
        +data() : <data>
}

class dataFixed {
        +data() : <data>
}

chunk o-- dataState
dataState <|-- dataFixed
dataState <|-- dataComputed

note right of chunk::data()
    data(dataState)
end note

@enduml
