@startuml
skinparam monochrome true
skinparam shadowing false
skinparam style strictuml
skinparam LifelineStrategy nosolid
skinparam sequenceMessageAlign center
title Work Request,\nPrerequisite Available Externally to the Store

box "Node x" #ffffff
participant Client as client
end box
box "Node y" #ffffff
participant Store as store
participant Worker as worker
end box
box "Node z" #ffffff
participant "Prerequsite Store" as pstore
end box
database "Location Service" as ls

client -> store ++: Request work
activate client
store -> store ++--: Set work state: PEND
store --> client: ACK
deactivate client
store -> store ++: Get prereq state
return UNAVAIL
store -> store ++--: Set prereq state association:\nAVAIL -> Launch work
store -> ls ++: Locate prerequisite
return Location of prerequisite
store -> pstore ++: Request prereq data
pstore --> store: Prereq data AVAIL
deactivate store
...
pstore --> store --: Prereq data
activate store
store -> store ++: Store data
store -> store ++: Set prereq data state: AVAIL
store -> store ++: Get prereq state associations
store -> worker **: Launch work
deactivate store
deactivate store
deactivate store
deactivate store
activate worker
|||
@enduml
